# Set application-specific parameters
NAME ?= MyApp
VERSION ?= 0.1

SOURCE_DIR ?= src
SOURCE_FILES ?= MyApp.app README COPYING

TEMPLATE_DMG ?= template.dmg

# Include the master makefile
include ../Makefile
